project_name: deb
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
release:
  prerelease: auto
  name_template: "{{ .Tag }}"
brews:
  - 
    tap:
      owner: debugged
      name: homebrew-tap
      branch: main
    goarm: 6
    homepage:  https://www.debugged.nl
    commit_author:
      name: toonvanstrijp
      email: toon@debugged.nl